force-app/main/default/objects/Custom_Parent__c/Custom_Parent__c.object-meta.xml
<CustomObject>
    <label>Custom Parent</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Custom Parent Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Custom Parents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Custom_Parent__c/fields/SYS_Key__c.field-meta.xml
<CustomField>
    <fullName>SYS_Key__c</fullName>
    <externalId>true</externalId>
    <label>SYS_Key</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HttpHeaders__mdt/HttpHeaders__mdt.object-meta.xml
<CustomObject>
    <label>HttpHeader</label>
    <pluralLabel>HttpHeaders</pluralLabel>
</CustomObject>

force-app/main/default/objects/HttpHeaders__mdt/SYS_Key__c.field-meta.xml
<CustomField>
    <fullName>SYS_Key__c</fullName>
    <externalId>true</externalId>
    <label>SYS_Key</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IntegrationSetting__mdt/IntegrationSetting__mdt.object-meta.xml
<CustomObject>
    <label>IntegrationSetting</label>
    <pluralLabel>IntegrationSettings</pluralLabel>
</CustomObject>

force-app/main/default/objects/IntegrationSetting__mdt/fields/BaseAPIEndPoint__c.field-meta.xml
<CustomField>
    <fullName>BaseAPIEndPoint__c</fullName>
    <label>BaseAPIEndPoint</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/IntegrationSetting__mdt/fields/UpdateMethod__c.field-meta.xml
<CustomField>
    <fullName>UpdateMethod__c</fullName>
    <defaultValue>&apos;POST&apos;</defaultValue>
    <label>UpdateMethod</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>POST</fullName>
                <default>true</default>
                <label>POST</label>
            </value>
            <value>
                <fullName>PUT</fullName>
            </value>
            <value>
                <fullName>PATCH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/SYS_IntegrationLog__c.object-meta.xml
<CustomObject>
    <label>SYS_IntegrationLog</label>
    <nameField>
        <displayFormat>I-{0000000000}</displayFormat>
        <label>SYS_IntegrationLog Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SYS_IntegrationLogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/WhatId__c.field-meta.xml
<CustomField>
    <fullName>WhatId__c</fullName>
    <label>WhatId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/override_SYS_ApplicationService.cls
public class override_SYS_ApplicationService extends SYS_ApplicationService {
    public override_SYS_ApplicationService() {

    }

    public override HttpResponse doOutbound(SYS_IntegrationLog__c log){
        System.debug('\n In override_SYS_ApplicationService');
        return super.doOutbound(log);
    }

    public override HttpRequest buildOutboundHttpRequest(SYS_IntegrationLog__c log){
        HttpRequest req = new HttpRequest();
        IntegrationSetting__mdt integrationSetting = SYS_DataCache.integrationSetting.get(SYS_Datacache.INT_TYPE);
        String baseEndpoint = integrationSetting.BaseAPIEndPoint__c;

        List<HttpHeaders__mdt> httpHeader = SYS_DataCache.headerSetting;
        req.setMethod(integrationSetting.UpdateMethod__c);
        for(HttpHeaders__mdt head:httpHeader){
            SYS_debug.log('header is = '+head.MasterLabel + ''+head.Value__c);
            req.setHeader(String.valueOf(head.MasterLabel), String.valueOf(head.Value__c));
                
        }
        String resourceUrl = integrationSetting.BaseAPIEndPoint__c+SYS_DataCache.objectSettingMap.get(SYS_DataCache.OBJ_TYPE).ResourcePath__c;
        List<Custom_Parent__c> rec = [SELECT SYS_Key__c FROM Custom_Parent__c WHERE Id = :log.WhatId__c LIMIT 1];
        req.setEndpoint(resourceUrl+'Id'+'/'+rec[0].SYS_Key__c);
        return req;
    }

}