force-app/main/default/objects/HttpHeaders__mdt/HttpHeaders__mdt.object-meta.xml
<CustomObject>
    <label>HttpHeader</label>
    <pluralLabel>HttpHeaders</pluralLabel>
</CustomObject>

force-app/main/default/objects/HttpHeaders__mdt/fields/IntegrationType__c.field-meta.xml
<CustomField>
    <fullName>IntegrationType__c</fullName>
    <label>IntegrationType</label>
    <referenceTo>IntegrationSetting__mdt</referenceTo>
    <relationshipLabel>HttpHeaders</relationshipLabel>
    <relationshipName>HttpHeaders</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/IntegrationSetting__mdt/IntegrationSetting__mdt.object-meta.xml
<CustomObject>
    <label>IntegrationSetting</label>
    <pluralLabel>IntegrationSettings</pluralLabel>
</CustomObject>

force-app/main/default/objects/IntegrationSetting__mdt/fields/BaseAPIEndPoint__c.field-meta.xml
<CustomField>
    <fullName>BaseAPIEndPoint__c</fullName>
    <label>BaseAPIEndPoint</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/IntegrationSetting__mdt/fields/UpdateMethod__c.field-meta.xml
<CustomField>
    <fullName>UpdateMethod__c</fullName>
    <defaultValue>&apos;POST&apos;</defaultValue>
    <label>UpdateMethod</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>POST</fullName>
                <default>true</default>
                <label>POST</label>
            </value>
            <value>
                <fullName>PUT</fullName>
            </value>
            <value>
                <fullName>PATCH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ObjectSetting__mdt/ObjectSetting__mdt.object-meta.xml
<CustomObject>
    <label>ObjectSetting</label>
    <pluralLabel>ObjectSettings</pluralLabel>
</CustomObject>

force-app/main/default/objects/ObjectSetting__mdt/fields/IntegrationType__c.field-meta.xml
<CustomField>
    <fullName>IntegrationType__c</fullName>
    <label>IntegrationType</label>
    <referenceTo>IntegrationSetting__mdt</referenceTo>
    <relationshipLabel>ObjectSettings</relationshipLabel>
    <relationshipName>ObjectSettings</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/ObjectSetting__mdt/fields/ResourcePath__c.field-meta.xml
<CustomField>
    <fullName>ResourcePath__c</fullName>
    <label>ResourcePath</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SYS_HttpBuilder.cls
public class SYS_HttpBuilder {

   /* public static HttpRequest getHttpRequest() {
        HttpRequest req = new HttpRequest();
        List<IntegrationSetting__mdt> integrationSetting = SYS_DataCache.integrationSetting;
        String baseEndpoint = integrationSetting[0].BaseAPIEndPoint__c;
        if(integrationSetting.size() != 0){
            List<HttpHeaders__mdt> httpHeader = [SELECT Id, MasterLabel, Label, IntegrationType__c, Value__c 
                                                 FROM HttpHeaders__mdt 
                                                 WHERE IntegrationType__c =: integrationSetting[0].id];
            req.setMethod(integrationSetting[0].UpdateMethod__c);
            for(HttpHeaders__mdt head:httpHeader){
                SYS_debug.log('header is = '+head);
                req.setHeader(String.valueOf(head.MasterLabel), String.valueOf(head.Value__c));
            }
        }
        return req;
    }*/

    public static HttpRequest getHttpRequestGET() {
        HttpRequest req = new HttpRequest();
        List<IntegrationSetting__mdt> integrationSetting = SYS_DataCache.integrationSetting;
        String baseEndpoint = integrationSetting[0].BaseAPIEndPoint__c;
        if(integrationSetting.size() != 0){
            List<HttpHeaders__mdt> httpHeader = [SELECT Id, MasterLabel, Label, IntegrationType__c, Value__c 
                                                 FROM HttpHeaders__mdt 
                                                 WHERE IntegrationType__c =: integrationSetting[0].id];
            req.setMethod('GET');
            for(HttpHeaders__mdt head:httpHeader){
                SYS_debug.log('header is = '+head);
                req.setHeader(String.valueOf(head.MasterLabel), String.valueOf(head.Value__c));
            }
        }
        return req;
    }

    public static String getResourceUrlFromObjectApi(String objApi){
        String resourceUrl = SYS_DataCache.integrationSetting[0].BaseAPIEndPoint__c;
        if(objApi != null || objApi != ''){
            List<ObjectSetting__mdt> objSetting = [SELECT Id, ResourcePath__c, masterlabel, ObjectApiName__c
                                                   FROM ObjectSetting__mdt WHERE ObjectApiName__c = : objApi 
                                                   and IntegrationType__r.DeveloperName = : SYS_DataCache.integrationSetting[0].developername];
            SYS_debug.log('resource url='+objSetting[0].ResourcePath__c);
            if(objSetting.size() != 0){
                resourceUrl += objSetting[0].ResourcePath__c;
            }
        }
        SYS_debug.log('resource url='+resourceUrl);
        return resourceUrl;
    }

    public static String getResourceReadUrl(String entityName, String entityId) {
        String resourceUrl = SYS_DataCache.integrationSetting[0].BaseAPIEndPoint__c;
        if(entityName != null || entityName != '') {
            String url = SYS_Constants.RESOURCE.replace('entityName' , entityName.toLowerCase()).replace('entityId' , entityId);
            resourceUrl += url;
        }
        SYS_debug.log('resource url---'+resourceUrl);
        return resourceUrl;
    }
}