force-app/main/default/objects/HttpHeaders__mdt/HttpHeaders__mdt.object-meta.xml
<CustomObject>
    <label>HttpHeader</label>
    <pluralLabel>HttpHeaders</pluralLabel>
</CustomObject>

force-app/main/default/objects/IntegrationSetting__mdt/IntegrationSetting__mdt.object-meta.xml
<CustomObject>
    <label>IntegrationSetting</label>
    <pluralLabel>IntegrationSettings</pluralLabel>
</CustomObject>

force-app/main/default/objects/IntegrationSetting__mdt/fields/BaseAPIEndPoint__c.field-meta.xml
<CustomField>
    <fullName>BaseAPIEndPoint__c</fullName>
    <label>BaseAPIEndPoint</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/IntegrationSetting__mdt/fields/UpdateMethod__c.field-meta.xml
<CustomField>
    <fullName>UpdateMethod__c</fullName>
    <defaultValue>&apos;POST&apos;</defaultValue>
    <label>UpdateMethod</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>POST</fullName>
                <default>true</default>
                <label>POST</label>
            </value>
            <value>
                <fullName>PUT</fullName>
            </value>
            <value>
                <fullName>PATCH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/SYS_IntegrationLog__c.object-meta.xml
<CustomObject>
    <label>SYS_IntegrationLog</label>
    <nameField>
        <displayFormat>I-{0000000000}</displayFormat>
        <label>SYS_IntegrationLog Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SYS_IntegrationLogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/data0__c.field-meta.xml
<CustomField>
    <fullName>data0__c</fullName>
    <label>data0</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/data1__c.field-meta.xml
<CustomField>
    <fullName>data1__c</fullName>
    <label>data1</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/data2__c.field-meta.xml
<CustomField>
    <fullName>data2__c</fullName>
    <label>data2</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/data3__c.field-meta.xml
<CustomField>
    <fullName>data3__c</fullName>
    <label>data3</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/data4__c.field-meta.xml
<CustomField>
    <fullName>data4__c</fullName>
    <label>data4</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/data5__c.field-meta.xml
<CustomField>
    <fullName>data5__c</fullName>
    <label>data5</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/data6__c.field-meta.xml
<CustomField>
    <fullName>data6__c</fullName>
    <label>data6</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/data7__c.field-meta.xml
<CustomField>
    <fullName>data7__c</fullName>
    <label>data7</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/data8__c.field-meta.xml
<CustomField>
    <fullName>data8__c</fullName>
    <label>data8</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/data9__c.field-meta.xml
<CustomField>
    <fullName>data9__c</fullName>
    <label>data9</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent</label>
    <referenceTo>SYS_IntegrationLog__c</referenceTo>
    <relationshipLabel>SYS_IntegrationLogs</relationshipLabel>
    <relationshipName>SYS_IntegrationLogs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/QB_Entity__c.field-meta.xml
<CustomField>
    <fullName>QB_Entity__c</fullName>
    <label>QB_Entity</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;NEW&quot;</defaultValue>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NEW</fullName>
            </value>
            <value>
                <fullName>DONE</fullName>
            </value>
            <value>
                <fullName>FAIL</fullName>
            </value>
            <value>
                <fullName>ERROR</fullName>
            </value>
            <value>
                <fullName>PENDING_PARENT</fullName>
            </value>
            <value>
                <fullName>READY_FOR_PROCESSING</fullName>
                <label>READY FOR PROCESSING</label>
            </value>
            <value>
                <fullName>WAITING_FOR_PARENT</fullName>
                <label>WAITING FOR PARENT</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/SYS_Http_Status__c.field-meta.xml
<CustomField>
    <fullName>SYS_Http_Status__c</fullName>
    <label>Http Status</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/SYS_IntegrationSettings__c.field-meta.xml
<CustomField>
    <fullName>SYS_IntegrationSettings__c</fullName>
    <label>SYS_IntegrationSettings</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Quickbooks</fullName>
            </value>
            <value>
                <fullName>JIRA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/SYS_Operation_Type__c.field-meta.xml
<CustomField>
    <fullName>SYS_Operation_Type__c</fullName>
    <label>SYS_Operation_Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MERGE</fullName>
            </value>
            <value>
                <fullName>DELETE</fullName>
            </value>
            <value>
                <fullName>UPSERT</fullName>
            </value>
            <value>
                <fullName>RESPONSE</fullName>
            </value>
            <value>
                <fullName>CDC</fullName>
            </value>
            <value>
                <fullName>INSERT</fullName>
            </value>
            <value>
                <fullName>UPDATE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/SYS_RequestId__c.field-meta.xml
<CustomField>
    <fullName>SYS_RequestId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RequestId</label>
    <referenceTo>SYS_IntegrationLog__c</referenceTo>
    <relationshipLabel>SYS_IntegrationLogs (RequestId)</relationshipLabel>
    <relationshipName>RequestId</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>INBOUND</fullName>
            </value>
            <value>
                <fullName>OUTBOUND</fullName>
            </value>
            <value>
                <fullName>RESPONSE</fullName>
            </value>
            <value>
                <fullName>MERGE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/WhatId__c.field-meta.xml
<CustomField>
    <fullName>WhatId__c</fullName>
    <label>WhatId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SYS_IntegrationLogOutboundQueueable.cls
public class SYS_IntegrationLogOutboundQueueable implements Queueable, Database.AllowsCallouts{ 
   
    private List<Id> sysLogIds = new List<Id>();
    
    public SYS_IntegrationLogOutboundQueueable(List<Id> idList){
        this.sysLogIds = idList;
    }
    public void execute(QueueableContext context){

        List<Id> sysLogResponse = new List<Id>(); //user to trigger the async class to update SyncToken from response.
        
        
        Http http = new Http();
        HttpRequest req = new HttpRequest();
        List<SYS_IntegrationLog__c> insertResponse = new List<SYS_IntegrationLog__c>();
        List<SYS_IntegrationLog__c> sysLog = [SELECT id,
                                              data0__c,
                                              data1__c,
                                              data2__c,
                                              data3__c,
                                              data4__c,
                                              data5__c,
                                              data6__c,
                                              data7__c,
                                              data8__c,
                                              data9__c,
                                              Type__c,WhatId__c,Parent__c,Order__c
                                              FROM SYS_IntegrationLog__c WHERE Id in:sysLogIds];
        //TODO - the below code will cosider parent__c look up as empty and order__c as empty. 
        List<IntegrationSetting__mdt> integrationSetting = SYS_DataCache.integrationSetting;
        String baseEndpoint = integrationSetting[0].BaseAPIEndPoint__c;
        List<sObject> recordList = new List<sObject>();
        //TODO - field for QB 
        //TODO - class for setting http req.
        //TODO - HTTPBuilder, SYS_IntegrationLogHandler global class(override for integration and prod specific)
        if(integrationSetting.size() != 0){
            List<HttpHeaders__mdt> httpHeader = SYS_DataCache.headerSetting;
            req.setMethod(integrationSetting[0].UpdateMethod__c);
            for(HttpHeaders__mdt head:httpHeader){
                SYS_debug.log('header is = '+head.MasterLabel + ''+head.Value__c);
                req.setHeader(String.valueOf(head.MasterLabel), String.valueOf(head.Value__c));
                
            } 
            
            for(SYS_IntegrationLog__c log:sysLog) {
                SYS_debug.log('inside for loop'+Id.valueof(log.WhatId__c).getsobjecttype());
                String body = log.data0__c != null ? log.data0__c : '' +
                            log.data1__c != null ? log.data1__c : '' +
                            log.data2__c != null ? log.data2__c : '' +
                            log.data3__c != null ? log.data3__c : '' +
                            log.data4__c != null ? log.data4__c : '' +
                            log.data5__c != null ? log.data5__c : '' +
                            log.data6__c != null ? log.data6__c : '' +
                            log.data7__c != null ? log.data7__c : '' + 
                            log.data8__c != null ? log.data8__c : '' +
                            log.data9__c != null ? log.data9__c : '' ; 
            
                
                Schema.SObjectType objectApiName = Id.valueof(log.WhatId__c).getsobjecttype();
                SYS_debug.log('sObject api name ='+objectApiName); 
                req.setEndpoint(SYS_HttpBuilder.getResourceUrlFromObjectApi( String.valueOf(objectApiName)));
                req.setBody(body);
                system.debug('body'+body);
                 
                //##Hit the webservice
                //TODO - Use limit api to avoid gov limit
                //TODO - add a method for response log
                HttpResponse resp = http.send(req);
                if(resp.getStatusCode() != 201){
                    SYS_debug.log('#### resp status: '+resp.getStatus());
                    SYS_debug.log('#### resp code: '+resp.getStatusCode()); 
                    SYS_debug.log('#### resp: '+resp.getBody());

                    SYS_IntegrationLog__c logResp = new SYS_IntegrationLog__c();//--M SYS_integrationLogHandler.getLogsToInsert(resp.getBody());
                    if (Schema.sObjectType.SYS_IntegrationLog__c.fields.Status__c.isCreateable()) {
                    logResp.Status__c = 'ERROR';
                    }
                    if (Schema.sObjectType.SYS_IntegrationLog__c.fields.SYS_Http_Status__c.isCreateable()) {
                    logresp.SYS_Http_Status__c = integer.valueOf(resp.getStatusCode());
                    }
                    if (Schema.sObjectType.SYS_IntegrationLog__c.fields.SYS_RequestId__c.isCreateable()) {
                    logResp.SYS_RequestId__c = log.Id;
                    }
                    if (Schema.sObjectType.SYS_IntegrationLog__c.fields.WhatId__c.isCreateable()) {
                    logResp.WhatId__c = log.WhatId__c;
                    }
                    // if (Schema.sObjectType.SYS_IntegrationLog__c.fields.QB_Entity__c.isCreateable()) {
                    logResp.QB_Entity__c = objectApiName + '';
                    
                    if (Schema.sObjectType.SYS_IntegrationLog__c.fields.Type__c.isCreateable()) {
                    logResp.Type__c = 'INBOUND';
                    }
                    if (Schema.sObjectType.SYS_IntegrationLog__c.fields.SYS_Operation_Type__c.isCreateable()) {
                    logResp.SYS_Operation_Type__c = 'RESPONSE';
                    }
                    if (Schema.sObjectType.SYS_IntegrationLog__c.fields.SYS_Operation_Type__c.isCreateable()) {
                        logResp.SYS_IntegrationSettings__c = SYS_Constants.INT_TYPE;
                    }
                    insertResponse.add(logResp);
                }
                else{
                    
                    SYS_IntegrationLog__c logResp = new SYS_IntegrationLog__c();//-- M SYS_integrationLogHandler.getLogsToInsert(resp.getBody());
                    if (Schema.sObjectType.SYS_IntegrationLog__c.fields.SYS_Http_Status__c.isCreateable()) {
                    logresp.SYS_Http_Status__c = Integer.valueOf(resp.getStatusCode());
                    }
                    if (Schema.sObjectType.SYS_IntegrationLog__c.fields.SYS_RequestId__c.isCreateable()) {
                    logResp.SYS_RequestId__c = log.Id;
                    }
                    if (Schema.sObjectType.SYS_IntegrationLog__c.fields.WhatId__c.isCreateable()) {
                    logResp.WhatId__c = log.WhatId__c;
                    }
                    // if (Schema.sObjectType.SYS_IntegrationLog__c.fields.QB_Entity__c.isCreateable()) {
                    logResp.QB_Entity__c = objectApiName + '';
                    // }
                    if (Schema.sObjectType.SYS_IntegrationLog__c.fields.Type__c.isCreateable()) {
                    logResp.Type__c = 'INBOUND';
                    }
                    if (Schema.sObjectType.SYS_IntegrationLog__c.fields.SYS_Operation_Type__c.isCreateable()) {
                        logResp.SYS_IntegrationSettings__c = SYS_Constants.INT_TYPE;
                    }
                    if (Schema.sObjectType.SYS_IntegrationLog__c.fields.SYS_Operation_Type__c.isCreateable()) {
                    logResp.SYS_Operation_Type__c = 'RESPONSE';
                    }
                    insertResponse.add(logResp);
                }
        	}
            
            if(insertResponse.size() > 0){
                SYS_debug.log('##insert all response logs');
                Database.SaveResult[] results = Database.insert(insertResponse, false);
                for(Database.SaveResult result : results){
                    if(result.isSuccess()){
                        sysLogResponse.add(result.getId());
                    } else {
                        SYS_debug.log('Insertion error has occured.');
                        for(Database.Error err : result.getErrors()) {
                            SYS_debug.log('The following error has occurred.');                    
                            SYS_debug.log(err.getStatusCode() + ': ' + err.getMessage());
                            SYS_debug.log('Fields affected are: ' + err.getFields());
                        }
                    }
                }
                //TODO - Add the queueable class to process response.
                //System.enqueueJob(new SYS_processResponse_QB(sysLogResponse));
                // SYS_processResponse_QB instance = new SYS_processResponse_QB(sysLogResponse);
                // if(SYS_Constants.INT_TYPE == 'Quickbooks')
                //     instance.updateSyncToken();
            } 
            
        } else {
            
        }
    }
   
}