force-app/main/default/objects/SYS_IntegrationLog__c/SYS_IntegrationLog__c.object-meta.xml
<CustomObject>
    <label>SYS_IntegrationLog</label>
    <nameField>
        <displayFormat>I-{0000000000}</displayFormat>
        <label>SYS_IntegrationLog Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SYS_IntegrationLogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/On_Complete_Handler__c.field-meta.xml
<CustomField>
    <fullName>On_Complete_Handler__c</fullName>
    <defaultValue>&quot;SYS_ApplicationService&quot;</defaultValue>
    <label>On Complete Handler</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SYS_ParentingQueueable.cls
public class SYS_ParentingQueueable implements Queueable{

    private String parentLog;
    private String integrationSetting;
    private SYS_IntegrationLog__c childLog;

    public SYS_ParentingQueueable(String parentLog,String integrationSetting,SYS_IntegrationLog__c childLog) {
        this.integrationSetting = integrationSetting;
        this.parentLog = parentLog;
        this.childLog = childLog;

    }

    public void execute(QueueableContext context){

        SYS_DataCache.INT_TYPE = integrationSetting;
        SYS_ApplicationService appService = (SYS_ApplicationService)Type.forName(this.childLog.On_Complete_Handler__c).newInstance();
        appService.fixParent(parentLog,childLog);
        

    }
}