force-app/main/default/objects/SYS_IntegrationLog__c/SYS_IntegrationLog__c.object-meta.xml
<CustomObject>
    <label>SYS_IntegrationLog</label>
    <nameField>
        <displayFormat>I-{0000000000}</displayFormat>
        <label>SYS_IntegrationLog Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SYS_IntegrationLogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/Custom_Apex_Handler__c.field-meta.xml
<CustomField>
    <fullName>Custom_Apex_Handler__c</fullName>
    <label>Custom Apex Handler</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/data0__c.field-meta.xml
<CustomField>
    <fullName>data0__c</fullName>
    <label>data0</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/data1__c.field-meta.xml
<CustomField>
    <fullName>data1__c</fullName>
    <label>data1</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/data2__c.field-meta.xml
<CustomField>
    <fullName>data2__c</fullName>
    <label>data2</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/data3__c.field-meta.xml
<CustomField>
    <fullName>data3__c</fullName>
    <label>data3</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/data4__c.field-meta.xml
<CustomField>
    <fullName>data4__c</fullName>
    <label>data4</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/data5__c.field-meta.xml
<CustomField>
    <fullName>data5__c</fullName>
    <label>data5</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/data6__c.field-meta.xml
<CustomField>
    <fullName>data6__c</fullName>
    <label>data6</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/data7__c.field-meta.xml
<CustomField>
    <fullName>data7__c</fullName>
    <label>data7</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/data8__c.field-meta.xml
<CustomField>
    <fullName>data8__c</fullName>
    <label>data8</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/data9__c.field-meta.xml
<CustomField>
    <fullName>data9__c</fullName>
    <label>data9</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/External_Id_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>External_Id_Field_API_Name__c</fullName>
    <description>This field is populated from webservice for Inbound only</description>
    <label>External Id Field API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/Flat_Key_for_Resource__c.field-meta.xml
<CustomField>
    <fullName>Flat_Key_for_Resource__c</fullName>
    <description>Defines the flat key in incoming JSON that will be used to identify the Resource and hence the object setting</description>
    <label>Flat Key for Resource</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/How_to_process__c.field-meta.xml
<CustomField>
    <fullName>How_to_process__c</fullName>
    <label>How to process?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>use_object_setting</fullName>
                <default>true</default>
                <label>Use Object Setting</label>
            </value>
            <value>
                <fullName>use_custom_apex_handler</fullName>
                <label>Use Custom Apex Handler</label>
            </value>
            <value>
                <fullName>ignore_log</fullName>
                <label>Ignore Log</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/ObjectSettingId__c.field-meta.xml
<CustomField>
    <fullName>ObjectSettingId__c</fullName>
    <label>ObjectSettingId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent</label>
    <referenceTo>SYS_IntegrationLog__c</referenceTo>
    <relationshipLabel>SYS_IntegrationLogs</relationshipLabel>
    <relationshipName>SYS_IntegrationLogs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/SYS_IntegrationSettings__c.field-meta.xml
<CustomField>
    <fullName>SYS_IntegrationSettings__c</fullName>
    <label>SYS_IntegrationSettings</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Quickbooks</fullName>
            </value>
            <value>
                <fullName>JIRA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/SYS_Operation_Type__c.field-meta.xml
<CustomField>
    <fullName>SYS_Operation_Type__c</fullName>
    <label>SYS_Operation_Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MERGE</fullName>
            </value>
            <value>
                <fullName>DELETE</fullName>
            </value>
            <value>
                <fullName>UPSERT</fullName>
            </value>
            <value>
                <fullName>RESPONSE</fullName>
            </value>
            <value>
                <fullName>CDC</fullName>
            </value>
            <value>
                <fullName>INSERT</fullName>
            </value>
            <value>
                <fullName>UPDATE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>INBOUND</fullName>
            </value>
            <value>
                <fullName>OUTBOUND</fullName>
            </value>
            <value>
                <fullName>RESPONSE</fullName>
            </value>
            <value>
                <fullName>MERGE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SYS_IntegrationLog__c/fields/WhatId__c.field-meta.xml
<CustomField>
    <fullName>WhatId__c</fullName>
    <label>WhatId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SYS_IntegrationLogInboundImmediate.cls
public class SYS_IntegrationLogInboundImmediate{ 
    
    private List<Id> sysLogIds = new List<Id>();
    
    public SYS_IntegrationLogInboundImmediate(List<Id> idList){
        this.sysLogIds = idList;
    }

    public void execute(){
        
        List<sObject> inboundResultLogs = new List<sObject>();
    
        List<SYS_IntegrationLog__c> sysLogs = 
                                            [SELECT 
                                                id,
                                                data0__c,
                                                data1__c,
                                                data2__c,
                                                data3__c,
                                                data4__c,
                                                data5__c,
                                                data6__c,
                                                data7__c,
                                                data8__c,
                                                data9__c,
                                                External_Id_Field_API_Name__c,
                                                How_to_process__c,Custom_Apex_Handler__c,SYS_Operation_Type__c,Flat_Key_for_Resource__c,
                                                Type__c,WhatId__c,Parent__c,Order__c,ObjectSettingId__c,SYS_IntegrationSettings__c
                                            FROM SYS_IntegrationLog__c 
                                            WHERE Id in:sysLogIds];
        
        for(SYS_IntegrationLog__c log:sysLogs) {
            
            
            SYS_DataCache.INT_TYPE = log.SYS_IntegrationSettings__c;
            // NA SYS_DataCache.OBJ_TYPE = log.ObjectSettingId__c;
            SYS_ApplicationService appService;
            
            if(log.How_to_process__c == 'use_object_setting')
                appService = (SYS_ApplicationService)Type.forName(SYS_DataCache.objectSettingMap.get(SYS_DataCache.OBJ_TYPE).ApexHandler__c).newInstance();
            else if(log.How_to_process__c == 'use_custom_apex_handler')
                appService = (SYS_ApplicationService)Type.forName(log.Custom_Apex_Handler__c).newInstance();
            else if(log.How_to_process__c == 'ignore_log'){
                continue;
            }
            else{
                //Log Message
                continue;
            }

            Boolean dmlResult = appService.doInbound(log);
            
            inboundResultLogs.add(appService.generatelogForInboundResult(dmlResult,log));

            /*
            if(log.SYS_Operation_Type__c.toUpperCase()=='INSERT'){
                inboundRecordsForInsert.add(appService.doInbound(log));   
            }
            else if(log.SYS_Operation_Type__c.toUpperCase()=='UPSERT'){

                String externalKey = SYS_DataCache.objectSettingMap.get(log.ObjectSettingId__c).ExternalFieldApi__c;
                String compositeKey = externalKey+'.'+SYS_DataCache.objectSettingMap.get(log.ObjectSettingId__c).ObjectApiName__c;
                if(inboundRecordsForUpsertMap.containsKey(compositeKey)){
                    List<sObject> existingRecordsForKey = inboundRecordsForUpsertMap.get(compositeKey);
                    existingRecordsForKey.add(appService.doInbound(log));
                    inboundRecordsForUpsertMap.put(compositeKey, existingRecordsForKey);
                }
                else{
                    inboundRecordsForUpsertMap.put(compositeKey, new List<sObject>());
                }
                       
            }
            else if(log.SYS_Operation_Type__c.toUpperCase()=='UPDATE'){
                inboundRecordsForUpdate.add(appService.doInbound(log));   
            }
            else if(log.SYS_Operation_Type__c.toUpperCase()=='DELETE'){
                inboundRecordsForDelete.add(appService.doInbound(log));   
            }
            else{
                // Non DML Operation Type. Handle DMLs; if any, in the extended class. 
            }
            */
            
        }

        if(inboundResultLogs.size()>0){
            new SYS_ApplicationService().doDML(inboundResultLogs,'UPSERT','');  
        }

        /*
        //TODO - upsert against external id - DONE
        //TODO - Check DML Limits

        if(inboundRecordsForUpsertMap.size()>0){
            for(String compositeKey : inboundRecordsForUpsertMap.keySet()){

                String objectApiName = compositeKey.substring(compositeKey.indexOf('.')+1,compositeKey.length());
                String externalFieldApiName = compositeKey.substring(0,compositeKey.indexOf('.'));
            
                SYS_ApplicationService.doDML(inboundRecordsForUpsertMap.get(compositeKey),'UPSERT',Schema.getGlobalDescribe().get(objectApiName).getDescribe().fields.getMap().get(externalFieldApiName)); 
            }
             
        }

        if(inboundRecordsForUpdate.size()>0){
            SYS_ApplicationService.doDML(inboundRecordsForUpdate,'UPDATE',NULL);  
        }

        if(inboundRecordsForDelete.size()>0){
            SYS_ApplicationService.doDML(inboundRecordsForDelete,'DELETE',NULL);  
        }
        */
        
        
    
    }
}